### ISSUE TITLE
As a user I want to specify the default container remote to be used during sync by a repository during creation

### ISSUE THREAD

**Issue by ajsween** [pulp/pulp-cli#228]
Currently when specifying the remote collection to be used by an Ansible repository during creation an exception is thrown that indicates the type does not match. The remote collection can only be specified successfully when creating a sync job.

**Comment by daviddavis** [comment]
Maybe I am misunderstanding but this seems to work for me:

```
pulp ansible remote create --name test --url $ANSIBLE_COLLECTION_REMOTE_URL
pulp ansible repository create --name test --remote test
```

It creates a collection remote and a repository with that remote.

**Comment by ajsween** [comment]
This is indeed what I did. I'll validate again today. The only difference was that I used the Collection remote and Collection requirements-file attribute.

**Comment by daviddavis** [comment]
If you're able to reproduce, paste in the commands and the error. It'll help us debug.

**Comment by ajsween** [comment]
I am no longer able to reproduce. I suspect it is because I stopped using `pulp/pulp:latest` due to a recent bug that threw an exception based on suspicious folder characters in temp filenames used by the workers during a sync. I am currently using `pulp/pulp:3.12` which apparently didn't have this as a problem.

Following were the commands I used:
`[user@server ~]$ pulp ansible remote -t "collection" create --name "test" --tls-validation False --download-concurrency 3 --url "https://galaxy.ansible.com/" --requirements "collections:\n  - pulp.pulp_installer\n  - pulp.squeezer"`
`[user@server ~]$ pulp ansible repository create --name "test" --remote "test"`
`[user@server ~]$ pulp ansible repository sync --name test`

I will add though that the `pulp ansible repository --help` print out indicates there is a type option for the `repository` subcommand but does not seem to indicate a way to specify a type that matches the `pulp ansible remote -t` argument options `[collection|role]`. What is the significance of the `pulp ansible repository --type` argument?
```
[user@server ~]$ pulp ansible repository --help
Usage: pulp ansible repository [OPTIONS] COMMAND [ARGS]...

Options:
  -t, --type [ansible]
  --help                Show this message and exit.

Commands:
  create
  destroy
  label
  list
  show
  sync     If remote is not specified sync will try to use the default...
  update
  version
```

**Comment by daviddavis** [comment]
> I suspect it is because I stopped using pulp/pulp:latest due to a recent bug that threw an exception based on suspicious folder characters in temp filenames used by the workers during a sync.

Ah yea, django broke everything with their latest 2.2.21 release. We're working on it here: https://pulp.plan.io/issues/8691

> What is the significance of the pulp ansible repository --type argument?

It's mostly for consistency. Other plugins have more than one type of repos. Also, like with remotes, there is more than one type of remote in ansible.

**Comment by ajsween** [comment]
My apologies, I just realized it was not `pulp ansible` but `pulp container` I had the type mismatch with.

```
[user@server ~]$ pulp container remote create --name docker --download-concurrency 3 --policy immediate --url "https://registry-1.docker.io" --upstream-name "pulp/pulp"
[user@server ~]$ pulp container repository create --name docker --remote docker
Error: {"remote":["Type for Remote 'docker' does not match Repository."]}
```
I realize I could have specified a type on creation of the repository however there is only one type of remote so how can there be a type mismatch?
```
[user@server ~]$ pulp container remote --help
Usage: pulp container remote [OPTIONS] COMMAND [ARG]...

Options:
  -t, --type [container]
...
```
```
[user@server ~]$ pulp container repository --help
Usage: pulp container repository [OPTIONS] COMMAND [ARG]...

Options:
  -t, --type [container|push]
...
```

**Comment by daviddavis** [comment]
Yup, it looks like this is still outstanding for pulp_container:

https://pulp.plan.io/issues/7795

CC @pulp/container-plugin

**Comment by mdellweg** [comment]
The change has been merged in pulp_container, and i believe the cli parts are already in place.

**Comment by mdellweg** [comment]
@ajsween can you confirm, this was fixed, please?

**Comment by ajsween** [comment]
I'll test this morning and post my results.

**Comment by ajsween** [comment]
It still isn't working when testing with pulp-cli 0.9.0 connecting to pulp:3.12 container. Should I be trying with pulp:latest?

**Comment by mdellweg** [comment]
It should be in pulp_container 2.6. Can you look at the output of pulp status what version the plugin is at?

**Comment by ajsween** [comment]
Pulp:3.12 is running:
pulp_container 2.5.2

Any idea when a new tagged release will come out for the container? I had tried using the :latest tag but it constantly broke everything as if it were a nightly.

**Comment by mdellweg** [comment]
I just rebuilt the container.

https://github.com/pulp/pulp-oci-images/runs/2683121618?check_suite_focus=true#step:5:186

**Comment by ajsween** [comment]
This issue is resolved. Container repository creation now allows mapping the repository to a default remote.
